import Header from "@/components/base/layout/header";
import ProviderWrapper from "@/components/base/ProviderWrapper";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-neutral-950 min-h-screen flex flex-col sans-serif`}
      >
        <ProviderWrapper>
          <Header />
          <main className="flex-grow">
            {children}
          </main>
        </ProviderWrapper>
      </body>
    </html>
  );
}
